server:
  port: 8080

spring:
  application:
    name: oauth-demo
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG